name: 'Multi-Platform Release Action'
description: 'Create and manage releases on GitHub and Gitea (including self-hosted instances)'
author: 'LiquidLogicLabs'
inputs:
  platform:
    description: 'Platform type (github|gitea). If not provided, will auto-detect from repository URL'
    required: false
    default: ''
  token:
    description: 'Platform token for authentication. Defaults to GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
  
  # Release configuration
  tag:
    description: 'Tag for the release. If omitted, the git ref will be used (if it is a tag)'
    required: false
    default: ''
  name:
    description: 'Name for the release. If omitted, the tag will be used'
    required: false
    default: ''
  body:
    description: 'Body for the release. Note: This input will have white space trimmed before and after it. Use bodyFile if you need a non-trivial markdown body'
    required: false
    default: ''
  bodyFile:
    description: 'Body file for the release. This should be the path to the file'
    required: false
    default: ''
  draft:
    description: 'Marks this release as a draft release. Set to true to enable'
    required: false
    default: 'false'
  prerelease:
    description: 'Marks this release as prerelease. Set to true to enable'
    required: false
    default: 'false'
  commit:
    description: 'Commit reference. This will be used to create the tag if it does not exist'
    required: false
    default: ''
  
  # Artifacts
  artifacts:
    description: 'Paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)'
    required: false
    default: ''
  artifactContentType:
    description: 'The content type of the artifact. Defaults to application/octet-stream'
    required: false
    default: ''
  replacesArtifacts:
    description: 'Indicates if existing release artifacts should be replaced'
    required: false
    default: 'true'
  removeArtifacts:
    description: 'Indicates if existing release artifacts should be removed'
    required: false
    default: 'false'
  artifactErrorsFailBuild:
    description: 'Indicates if artifact read or upload errors should fail the build'
    required: false
    default: 'false'
  
  # Release management
  allowUpdates:
    description: 'Indicates if we should update a release if it already exists. Defaults to false'
    required: false
    default: 'false'
  skipIfReleaseExists:
    description: 'When enabled, the action will be skipped if a non-draft release already exists for the provided tag'
    required: false
    default: 'false'
  updateOnlyUnreleased:
    description: 'When allowUpdates is enabled, this will fail the action if the release it is updating is not a draft or a prerelease'
    required: false
    default: 'false'
  
  # Release notes
  generateReleaseNotes:
    description: 'Indicates if release notes should be automatically generated'
    required: false
    default: 'false'
  generateReleaseNotesPreviousTag:
    description: 'Previous tag to use when generating release notes. This will limit the release notes to changes between the two tags'
    required: false
    default: ''
  
  # Advanced options
  repository:
    description: 'Repository in owner/repo format (e.g., LiquidLogicLabs/git-action-release). If provided, takes precedence over owner and repo inputs'
    required: false
    default: ''
  owner:
    description: 'Optionally specify the owner of the repo where the release should be generated. Defaults to current repo owner'
    required: false
    default: ''
  repo:
    description: 'Optionally specify the repo where the release should be generated. Defaults to current repo'
    required: false
    default: ''
  omitBody:
    description: 'Indicates if the release body should be omitted'
    required: false
    default: 'false'
  omitBodyDuringUpdate:
    description: 'Indicates if the release body should be omitted during updates. The body will still be applied for newly created releases'
    required: false
    default: 'false'
  omitDraftDuringUpdate:
    description: 'Indicates if the draft flag should be omitted during updates. The draft flag will still be applied for newly created releases'
    required: false
    default: 'false'
  omitName:
    description: 'Indicates if the release name should be omitted'
    required: false
    default: 'false'
  omitNameDuringUpdate:
    description: 'Indicates if the release name should be omitted during updates. The name will still be applied for newly created releases'
    required: false
    default: 'false'
  omitPrereleaseDuringUpdate:
    description: 'Indicates if the prerelease flag should be omitted during updates. The prerelease flag will still be applied for newly created releases'
    required: false
    default: 'false'
  
  # Logging
  verbose:
    description: 'Enable verbose debug logging. Also enabled when ACTIONS_STEP_DEBUG=true.'
    required: false
    default: 'false'
  skipCertificateCheck:
    description: 'Skip TLS certificate verification for API calls (self-hosted instances).'
    required: false
    default: 'false'
outputs:
  id:
    description: 'The identifier of the created release'
  htmlUrl:
    description: 'The HTML URL of the release'
  uploadUrl:
    description: 'The URL for uploading assets to the release'
  tarballUrl:
    description: 'The URL for downloading the release as a tarball (.tar.gz)'
  zipballUrl:
    description: 'The URL for downloading the release as a zipball (.zip)'
  assets:
    description: 'JSON string containing a map of asset names to download URLs for uploaded assets'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'blue'
